---
version: '3.7'
services:
  app:
    image: "app-amadeu"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - amadeu-net
  db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=4linux
      - MYSQL_USER=amadeu
      - MYSQL_DATABASE=dexter
      - MYSQL_PASSWORD=pitagoras
    networks:
      - amadeu-net
networks:
  amadeu-net:
    external: true

